assignment:
  course: 'Course'
  semester: 'Semester'
  assignment_title: 'Assignment Title'
  assignment_short: 'Short Title'
  feedback_url: 'https://eng.anu.edu.au/courses/engnfeedback/ENGNXXXX/2019-SX/XXXX'
  grade_final_out_of: 100

# what type of feedback is this running
# at this stage, marks and tmc are not compatible (one should be true, one false)
feedback_type:
  json: False      # generate the json team list for wattle
  marks: False     # straight grading from wattle database 
  tmc: False      # include a team member contribution?
  group: False    # include the group marking
  wattle: False    # create a csv to upload to Wattle
  analysis: False # create an analysis file for markers
  many_eyes: False # create a many eyes report
  course: False # where collecting course feedback

# how will the crit be displayed
crit_display:
  text: True
  label: True
  scale: False
  graph: True
  rubric: True   # put rubric on the last page
  rubric_new_page: True

# messages in the pdf
pdf_messages:
  comment_title: 'Qualitative feedback on your work'
  indicator_title: 'Indication against the criteria'
  indicator_note: "*The indicators refer to categories described in the Assessment Guide.*"
  rubric_title: 'Indication against the rubric'
  rubric_note: '*Note: highlights indicate the level achieved for each criterion. Where multiple levels are highlighted, your work shows aspects of both.*'
  tmc_header_1: 'Team Member Contributions'
  tmc_header_2: 'Feedback from your team members'
  tmc_confidential: 'Confidential feedback' 


# variables for the pdf
tmc_pdf:
  eval_header: 'Peer evaluation of contribution by team members'
  team_count_message: 'true'
  count_message: 'team members submitted reviews.'
  member_header: "Team member"
  member_no_comment: "No comment"
  tmc_chart_caption: "*Note: the values have been generated by members of your team. These are not 'marks', instead given for 'information'.*"

# variables for the audit_graphs
audit_chart:
  # these values are the values in the Wattle file. Find labels will replaced with Replace values for the graph
  find_labels: ['Below Baseline', 'Baseline', 'Baseline-Acceptable', 'Acceptable', 'Acceptable-Exemplary', 'Exemplary']
  replace_values: [-2, 0.1, 1, 2, 3, 4]
  find_client_labels: ['Well below expectations', 'Below expectations', 'About expectations', 'Above expectations', 'Well above expectations']
  replace_client_values: [-2, -0.5, 0.5, 2, 3.5]
  # x and y axis titles
  x_axis_title: 'Audit criteria'
  y_axis_title: 'Perceived performance'
  # corresponding values for display on the tmc graph. min = -2, max = +2
  y_tick_values: [-2,-0,2,4]
  y_tick_labels: ["Below Baseline", "Baseline" ,"Acceptable", "Exemplary",]
  anon_legend: 'reviewer' # the anon label shown in the legend
  colormap: 'viridis' # colormap to use in the graph

# variables for the tmc_graphs
tmc_chart:
  # these values are the values in the Wattle file. Find labels will replaced with Replace values for the graph
  find_labels: ['At expectations', 'Meets expectations', 'Well above expectations', 'Well below expectations', 'Above expectations', 'Below expectations', 'Absent']
  replace_values: [0.1, 0.1, 1.5, -1.5, 0.75, -0.75, -2]
  # x and y axis titles
  x_axis_title: 'Team members'
  y_axis_title: 'Contributions to the team'
  # corresponding values for display on the tmc graph. min = -2, max = +2
  y_tick_values: [-2,-1.5,-0.75,0,0.75,1.5]
  y_tick_labels: ["absent", "well below" ,"below", "about", "above", "well above"]
  anon_legend: 'reviewer' # the anon label shown in the legend
  colormap: 'viridis' # colormap to use in the graph

crit_chart:
  grade_mean: "Mean Grade"
  wc: "word count"
  sc: "sentences"
  flesch: "FleschReadingEase"

many_eyes:
  eyes: ['self', 'shadow', 'tutor', 'client']

# variables for the pdf
audit_pdf:
  audit_chart_header: 'Indication of performance by stakeholders'
  audit_chart_caption: ''

# front_matter in the pdf read into the file
pdf_front_matter:
  copyright: 'Created with VirtuousLoop'

aylien:
  api_key: 'f68794f5973dcc7201e3bbf2d65f0928'
  api_id: 'da338871'
  endpoints: ["sentiment", "entities", "hashtags", "summarize"]
  endpoint_name: ["polarity", "entities", "hashtags", "sentences"]
  endpoint_title: ["Sentiment", "Keywords", "Hashtags", "Sentences"]

# variables for the analysis
analytics:
  readability_stats: [['wc', 'sentence info', 'words'],['sc', 'sentence info', 'sentences'],['flesch', 'readability grades', 'FleschReadingEase']]
  nlp_source_comment: "Extracted using the Aylien NLP API"
  filename: "marker_analytics" # the output name for the file
  analytics_header: "Analytics for all markers"
  grade_chart_header: "Average grades by marker"
  grade_chart_comment: "Mean grade awarded by marker"
  grade_table_header: "Descriptive statistics"
  grade_table_comment: "Descriptive statistics of grades awarded by marker. 'Overall' excludes 'No submission'"
  rubric_header: "Distribution by criterion"
  rubric_comment: "Graph of rubric distribution"
  readability_header: " Readability Statistics on comments"
  readability_comment: "for all comments, extracted using the Aylien NLP API"
  sentiment_header: "Sentiment Analysis of comments"
  summary_header: "Data extracted on comments"

load_file:
  students:
    rename: {"user id":"user", "uniid":"user", "first_name":"firstname", "first":"firstname", "surname":"lastname", "projectteam":"group"}
    required: ["user", "firstname", "lastname", "group"]
    index: "user"
    expected: ""
  marks:
    rename: {"username":"marker_id", "user":"marker"}
    required: ["user", "list_name"]
    index: "user"
    expected: "crit"
  fields:
    rename: {}
    required: ["field", "label"]
    index: "field"
    expected: ""
  crit_levels:
    rename: {"level":"index"}
    required: ["index", "text"]
    index: "index"
    expected: ""
  data_tmc:
    rename: {"teamdropdown":"list_team", "list":"list_team"}
    required: ["list_team", "user"]
    index: "username"
    expected: ""
  data_self:
    rename: {"crita":"crit_a", "critb":"crit_b", "confidential_comments":"comment_confidential"}
    required: ["team", "crit_a", "crit_b", "crita_text", "critb_text"]
    index: "username"
    expected: "labels"
  data_shadow:
    rename: {"crita":"crit_a", "critb":"crit_b", "confidential_comments":"comment_confidential"}
    required: ["team", "crit_a", "crit_b", "crita_text", "critb_text"]
    index: "username"
    expected: "labels"
  data_tutor:
    rename: {"list":"team", "commentgood":"comment_a", "commentimprove":"comment_b"}
    required: ["team", "username"]
    index: 
    expected: "crit"
  data_client:
    rename: {"crita":"crit_a", "critb":"crit_b", "critc":"crit_c", "critd":"crit_d", "crite":"crit_e", "critf":"crit_f", "commentgood":"comment_a", "commentimprove":"comment_b", "confidential":"comment_confidential", "q5":"team", "q1_1":"crit_a", "q1_2":"crit_b", "q1_3":"crit_c", "q1_4":"crit_d", "q1_5":"crit_e", "q1_6":"crit_f", "q2":"comment_a", "q3":"comment_b", "q4":"comment_confidential"}
    required: ["team"]
    index: 
    expected: "crit"
  data_conv:
    rename: {}
    required: []
    index: 
    expected: "crit"
  feedback_course:
    rename: {"tutor"}
    required: ["tutor_name"]
    index: 
    expected: "crit"
